### ISSUE TITLE
on initial load of slider if we click on first dot with stopAutoPlayOnSlide set as false, it stops working correctly(note: this happens only when slider just loads and hasn't removed hide-slides class from remaining slides)  

### ISSUE THREAD

**Issue by SachinB123** [dockleryxk/ng-simple-slideshow#38]
on initial load of slider if we click on first dot after it has moved to second or third dot with stopAutoPlayOnSlide set as false, it stops working correctly(note: this happens only when slider just loads and hasn't removed 'hide-slide' class from remaining slides).

A proposed solution would be to remove 'hide-slide' class and instead just provide those non selected class with 'right-slide' class but of course this is proposed as temporary hack and it would be better if you resolved it in your package internally

**Comment by dockleryxk** [comment]
@SachinB123 thank you for finding this! When you say "stops working correctly," do you mean that it stops auto-playing even though it should not?

**Comment by SachinB123** [comment]
No, whether it autoplays or not that is not the issue.

This issue can be reproduced on your demo page in following steps:
1. Open your demo page, click second or any dot other than first dot initially.
2.Then click back the first dot, it loads the image which is set on the the last slide of slide array.
3. If autoPlay is on along with stopAutoPlayOnSlide set as false, until the slideshow completes first round of slide array traversal that last slide array image remains stuck.
4.When first round of slide array is traversed, then it starts working perfectly fine and there is no problem thereafter. Problem only occurs in first round and consecutive rounds are error free.

Note: Problem only occurs in initial or first round of slide traversal using dots only but not with arrows, arrows based traversal works fine.

Only possible solution, I could find for this is that initially, not loaded slides are hidden using 'hide-slide' class, so I removed them and in their place I added 'right-slide' class that you had inside your package with left:100% defined which solved it temporarily but since it is an issue so I opened it here.

**Comment by dockleryxk** [comment]
@SachinB123 thank you for this information. I will likely not have time to look into this until this weekend, but I will let you know once I have it resolved.

**Comment by alex-osman** [comment]
This could use a fix

**Comment by dockleryxk** [comment]
I think this might just be fixed now, need to verify

**Comment by bttb** [comment]
it's definitely not fixed. Will try to investigate tomorrow. another problem I see is that on lazy load it first loads the first image, and then after you slide to another image it loads all other images in one go.

**Comment by bttb** [comment]
Okay, I have a solution. How can I push it?

**Comment by dockleryxk** [comment]
@bttb that's awesome! Just make a PR.

FYI: the original intention of `lazyLoad` was to ensure the rest of the page loaded after everything else, but not necessarily on a slide-by-slide basis. However, that functionality is more closely aligned with what people expect out of lazy loading, so I'm all for it!
