### ISSUE TITLE
add eventemitter onImageClicked

### ISSUE THREAD

**Issue by metalllus** [dockleryxk/ng-simple-slideshow#90]
Hi, would it be possible to add a new event emitter that would emit clicked image index in the source array upon image click?

I know you have the clickAction property but I wasn't able to figure out how to use it to listen to image clicks and send the clicked image index to the angular component where the slideshow is actually used.

**Comment by dockleryxk** [comment]
@metalllus I can add this. For now you could listen for clicks on the slideshow element and then check the index when this happens.

**Comment by metalllus** [comment]
> @metalllus I can add this. For now you could listen for clicks on the slideshow element and then check the index when this happens.

The important thing for me is to emit the event only when the center part of the image is clicked and not when the arrow parts are clicked on the sides if that would be possible.

**Comment by dockleryxk** [comment]
@metalllus yeah, that's exactly what I was thinking! My suggestion was just a workaround

**Comment by dockleryxk** [comment]
available in 1.3.0-beta.4

**Comment by metalllus** [comment]
If this is the onClick event, the event gets fired but it refreshes my browser window for some reason.

**Comment by metalllus** [comment]
if I use the 1.3.0-beta.4 version and click the image I get the browser window refresh every time even if I do not use the new onClick event at all.

**Comment by dockleryxk** [comment]
@metalllus do your images have click actions? It works fine on the demo (open the console and click on the slideshow) https://ng-simple-slideshow.firebaseapp.com/

**Comment by metalllus** [comment]
I do not know what the problem is, I created a very simple slideshow for testing, only two inputs used, [imageUrls] pointing to a list with two strings with imageUrls and [minHeight] input set to 440px. Still, on image click I get browser refresh. If I click the arrows, everything works fine, next image gets displayed. But if I click the center portion of the image, I get browser refresh.

**Comment by dockleryxk** [comment]
Can you make a reproduction on StackBlitz or something? I tried but can't recreate your isse

**Comment by metalllus** [comment]
Damn, that's a shame. I will dig deeper when I have time. Thx for the effort anyway.

**Comment by dockleryxk** [comment]
@metalllus if you want, just paste your component.ts file, maybe I'll see something obvious

**Comment by metalllus** [comment]
In the template I have only this:
`<slideshow
  [imageUrls]="imageUrls"
  [minHeight]="'440px'"
>
</slideshow>`

In the component:

`@Component({
  selector: 'app-welcome',
  templateUrl: './welcome.component.html',
  styleUrls: ['./welcome.component.css'],

})
export class WelcomeComponent implements OnInit {
  imageUrls = [
    'https://storage.googleapis.com/pezinsky-baby-sekac.appspot.com/thumb%40600_1571040552480-122041324-moon-stars-with-sleep-lettering-patch-bedtime-stitched-frame-flat-sticker-night-sky-sticker.jpg?GoogleAccessId=firebase-adminsdk-sncih%40pezinsky-baby-sekac.iam.gserviceaccount.com&Expires=3589660800&Signature=pdLfFW6HYTcNvl1oz5U3U9s0u%2Fo7%2B9Pa4msa8ciGi7GN4Z1ylApilx%2FR7p%2Fjfq%2Fd93aceq8eaAksgwhEc5qohOaMBq7jh2rghlA%2BWtbdrp8%2BlY4JD86wiV3qTFQt3n8ygbAkOopuk%2Fls1OZtNF71%2F0kjkgojieEGl8o5qzR3Gc%2F7UlFilmwONodku4mn%2FsB74lNCAIzguYVLoNPXCtdMNRbpEY%2FSWOTw3b5fqLvIaAL6mZUf3g9h7UtoKpw0Q5q6biQnrlLaPBma1ghX5uZu2rpFmuTq2YSbp%2FfghCi%2B7ok3vU1PgW4eqvbfGhWbaiuwOxM2%2FjoNGHRi7J6PkTga2g%3D%3D',
    'https://storage.googleapis.com/pezinsky-baby-sekac.appspot.com/thumb%40600_1568902238199-1559244390-best-toys-2019-walking-buzz-1559244376.jpg?GoogleAccessId=firebase-adminsdk-sncih%40pezinsky-baby-sekac.iam.gserviceaccount.com&Expires=3589660800&Signature=JMJNJ01RfqKeXj29xCFfHvwuEA%2BdtMCmqAvWj%2Bd%2F%2FU%2FZJE3JKPg79kNVP4JL2OSQ1xLR4vNK79xvliBVjEhoN8dNfED%2FrSnRt%2BfsbQSocZPpCbIpJ7HDkAARO0lqDNtQIf4jHitJaWUTIkpgJO8Bl5PMglTKmP7QehcsYM4WMRNfMLBwlA9micmiaCHu68wsclRCt2O2omkptq8iiywWTpBLnwujp5kkwYG%2Bl8mPiQ%2BDNZM7tb2X%2FU0vRmudJZ3VxT1WhhsScfbXu%2B61s23xxjrKduCWzw0PXSK1bHJdCb%2BK6fdFSIN4oSh7dJTPw3GUrw4NkvFQn7wO%2FQSrQ23n9A%3D%3D'
  ];


  constructor() { }

  ngOnInit() {
  }
}`

**Comment by metalllus** [comment]
I sent you an email with a screenshot, please have a look.

**Comment by dockleryxk** [comment]
@metalllus this is fixed in beta 7. I prevent the click default

**Comment by metalllus** [comment]
Works flawlessly now. Thx for hanging in there :)

S pozdravom / Best Regards,
Ľuboš Valkovič
Freelance Translator and Linguist
Ing. Ľuboš Valkovič
Kalinčiakova 1730/2
953 01 Zlaté Moravce
IČO: 43960707  
DIČ: 1078781374
Blog:        www.blogick.sk [http://www.blogick.sk/]
Tel. :       +421 905 870 436
e-mail:   lubos.valkovic@gmail.com [mailto:lubos.valkovic@gmail.com]
On 3. 11. 2019 22:46:51, Richard Jeffords <notifications@github.com> wrote:
@metalllus [https://github.com/metalllus] this is fixed in beta 7. I prevent the click default

**Comment by metalllus** [comment]
Hi, today I ran into another problem with the onClick event. If I have multiple slideshows on page and I click on an image on any of them, every slideshow on page triggers the onClick event. Could this be fixed somehow?

S pozdravom / Best Regards,
Ľuboš Valkovič
Freelance Translator and Linguist
Ing. Ľuboš Valkovič
Kalinčiakova 1730/2
953 01 Zlaté Moravce
IČO: 43960707  
DIČ: 1078781374
Tel. :       +421 905 870 436
E-mail:   lubos.valkovic@gmail.com [mailto:lubos.valkovic@gmail.com]
On 3. 11. 2019 22:46:51, Richard Jeffords <notifications@github.com> wrote:
@metalllus [https://github.com/metalllus] this is fixed in beta 7. I prevent the click default

**Comment by dockleryxk** [comment]
@metalllus interesting. It sounds like they are sharing the same service. I'll have to look into it

**Comment by metalllus** [comment]
Is this a deeper problem, will it take longer to fix?

S pozdravom / Best Regards,
Ľuboš Valkovič
Freelance Translator and Linguist
Ing. Ľuboš Valkovič
Kalinčiakova 1730/2
953 01 Zlaté Moravce
IČO: 43960707  
DIČ: 1078781374
Tel. :       +421 905 870 436
E-mail:   lubos.valkovic@gmail.com [mailto:lubos.valkovic@gmail.com]
On 19. 11. 2019 14:51:34, Richard Jeffords <notifications@github.com> wrote:
@metalllus [https://github.com/metalllus] interesting. It sounds like they are sharing the same service. I'll have to look into it

**Comment by metalllus** [comment]
hi, did you make any progress on fixing the issue I reported? Unfortunately, I came across another bug caused by the very same thing. If I create three slideshows on one page and I swipe left or right to get to the next image, the next image gets displayed on all the slideshows, not on just the one I swiped. If I use the arrows to move between images, everything works fine. But the swipe motion controls all the slideshows at the same time, not just the one you swipe on. If you make any progress on this please let me know. I would desperately need this to work.

S pozdravom / Best Regards,
Ľuboš Valkovič
Freelance Translator and Linguist
Ing. Ľuboš Valkovič
Kalinčiakova 1730/2
953 01 Zlaté Moravce
IČO: 43960707  
DIČ: 1078781374
Tel. :       +421 905 870 436
E-mail:   lubos.valkovic@gmail.com [mailto:lubos.valkovic@gmail.com]
On 19. 11. 2019 14:51:34, Richard Jeffords <notifications@github.com> wrote:
@metalllus [https://github.com/metalllus] interesting. It sounds like they are sharing the same service. I'll have to look into it

**Comment by dockleryxk** [comment]
this is fixed in beta.9!

**Comment by metalllus** [comment]
Great, pls make it available on npm, i still see only beta.8 there. Thank
you very much.

**Comment by dockleryxk** [comment]
It should be available. I published it

**Comment by metalllus** [comment]
S pozdravom / Best Regards,
Ľuboš Valkovič
Freelance Translator and Linguist
Ing. Ľuboš Valkovič
Kalinčiakova 1730/2
953 01 Zlaté Moravce
IČO: 43960707  
DIČ: 1078781374
Tel. :       +421 905 870 436
E-mail:   lubos.valkovic@gmail.com [mailto:lubos.valkovic@gmail.com]
On 16. 12. 2019 14:08:09, Richard Jeffords <notifications@github.com> wrote:
It should be available. I published it

**Comment by metalllus** [comment]
Hi, could you kindly make a quick update to add support for Angular 9? It is a very simple update a few lines of code. Thank you in advance.

S pozdravom / Best Regards,
Ľuboš Valkovič
Freelance Translator and Linguist
Ing. Ľuboš Valkovič
Kalinčiakova 1730/2
953 01 Zlaté Moravce
IČO: 43960707  
DIČ: 1078781374
Tel. :       +421 905 870 436
E-mail:   lubos.valkovic@gmail.com [mailto:lubos.valkovic@gmail.com]
On 16. 12. 2019 14:08:09, Richard Jeffords <notifications@github.com> wrote:
It should be available. I published it
